safe:                             false
baseurl:                          /
url:                              "http://localhost:4000"

# ========================================

name:                             Hudson Marinho
description:                      "My personal website where I talk about front-end, development like HTML5, javascript, CSS3, thoughts, projects and photography"
about-me:                         "Hi, I’m Hudson Marinho. I'm 25 year old and am front-end developer who live in Natal/RN and working for company based in SP."
domain:                           "http://hudsonmarinho.com"
email:                            "hudsonmarinhodev@gmail.com"
twitter-username:                 "hudsonmarinho"
facebook-username:                "hudson.marinho"
feedburnerurl:                    "http://feeds.feedburner.com/hudsonmarinho"
google-analytics-tracking-id:     "UA-4005600-22"

# ========================================

markdown: kramdown
paginate: 5
permalink: blog/:year/:month/:day/:title/
highlighter: true

# ========================================

excerpt_separator: "<!-- more -->"
