# Site wide configuration

title: Hudson Marinho - Front end developer
locale: en_US
description: "Hi, I’m Hudson Marinho. I'm 25 year old and am front-end developer who live in Natal/RN and working for company based in SP."
logo: "http://graph.facebook.com/hudsonmarinho/picture?width=300&height=300"
search: true
url: http://hudsonmarinho.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner

owner:
  name: Hudson Marinho
  username: hudsonmarinho
  avatar: "http://graph.facebook.com/hudsonmarinho/picture?width=300&height=300"
  email: hudsonmarinhodev@gmail.com
  disqus-shortname: hudsonmarinho
  twitter: hudsonmarinho
  facebook: hudsonmarinho
  github: hudsonmarinho
  stackexchange: http://stackoverflow.com/users/2765176/hudson-marinho
  linkedin: hudsonmarinho
  instagram: hudsonmarinho
  flickr: hudsonmarinho
  tumblr: hudsonmarinho
  google:
    plus: hudsonmarinhodev
    analytics: "UA-4005600-22"
    verify:
    ad-client:
    ad-slot:
  bing-verify:
